# -*- coding: utf-8 -*-
"""Pyhton.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xQmSlwonul6eqseu6ueIJ0OTOYr4cnwI
"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Monthly Revenue
df = pd.read_csv("results_monthly_revenue.csv")
plt.plot(df["month"], df["revenue"])
plt.title("Monthly Revenue")
plt.xticks(rotation=45)
plt.savefig("chart_monthly_revenue.png")
plt.close()

# 2. Top Products by Revenue
df = pd.read_csv("results_top_products.csv")
plt.barh(df["product_name"], df["revenue"])
plt.title("Top Products by Revenue")
plt.savefig("chart_top_products.png")
plt.close()

# 3. Return Rate by Product
df = pd.read_csv("results_return_rates.csv")
plt.barh(df["product_name"], df["return_rate_pct"])
plt.title("Return Rate by Product")
plt.savefig("chart_return_rates.png")
plt.close()

# 4. Average Order Value by City
df = pd.read_csv("results_aov_by_city.csv")
plt.barh(df["city"], df["avg_order_value"])
plt.title("Average Order Value by City")
plt.savefig("chart_aov_by_city.png")
plt.close()

# 5. Cohort Repeat Purchase Rate
df = pd.read_csv("results_cohort_repeat.csv")
plt.bar(df["cohort_month"], df["repeat_rate_pct"])
plt.title("Repeat Purchase Rate by Cohort")
plt.xticks(rotation=45)
plt.savefig("chart_cohort_repeat.png")
plt.close()

print("Done - 5 charts saved.")